apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: springcommunity/spring-petclinic-vets-service
        resources:
          limits:
            memory: 512M
        ports:
        - containerPort: 8080
---
apiVersions: v1
kind: Service
metadata:
  name: vets-service-service
spec:
  selector:
    app: vets-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort