apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit-service
  template:
    metadata:
      labels:
        app: visit-service
    spec:
      containers:
        - name: visit-service
          image: visit-service:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: visit-service
spec:
  selector:
    app: visit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort